name: perl-Module-Build-Using-PkgConfig
upstream: http://search.cpan.org/dist/Module-Build-Using-PkgConfig/
description: Extend Module
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
