name: perl-Config-Auto
upstream: http://search.cpan.org/dist/Config-Auto/
description: Magical config file parser
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
