name: perl-MooseX-Configuration
upstream: http://search.cpan.org/dist/MooseX-Configuration/
description: Define attributes which come from configuration files
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
