name: perl-CGI-Application-Standard-Config
upstream: http://search.cpan.org/dist/CGI-Application-Standard-Config/
description: CGI
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
