name: perl-CGI-Application-Plugin-ConfigAuto
upstream: http://search.cpan.org/dist/CGI-Application-Plugin-ConfigAuto/
description: Easy config file management for CGI
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
