name: perl-MooseX-SimpleConfig
upstream: http://search.cpan.org/dist/MooseX-SimpleConfig/
description: Moose role for setting attributes from a simple configuration file
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
