name: perl-MooX-ConfigFromFile
upstream: http://search.cpan.org/dist/MooX-ConfigFromFile/
description: Moo eXtension for initializing objects from config file
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
