name: perl-Config-Any
upstream: http://search.cpan.org/dist/Config-Any/
description: Load configuration from different file formats, transparently
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
