name: perl-CGI-Application-Plugin-LinkIntegrity
upstream: http://search.cpan.org/dist/CGI-Application-Plugin-LinkIntegrity/
description: Make tamper-resisistent links in CGI
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
