name: perl-Config-ZOMG
upstream: http://search.cpan.org/dist/Config-ZOMG/
description: Yet Another Catalyst
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
