name: perl-CGI-Application-Plugin-DBIC-Schema
upstream: http://search.cpan.org/dist/CGI-Application-Plugin-DBIC-Schema/
description: Easy DBIx
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
