name: perl-MooX-File-ConfigDir
upstream: http://search.cpan.org/dist/MooX-File-ConfigDir/
description: Moo eXtension for File
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
