name: perl-DBIx-Class-Schema-Config
upstream: http://search.cpan.org/dist/DBIx-Class-Schema-Config/
description: Credential Management for DBIx
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
