name: perl-Config-INI-Reader-Multiline
upstream: http://search.cpan.org/dist/Config-INI-Reader-Multiline/
description: Parser for .ini files with line continuations
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
