name: perl-CGI-Application-Plugin-Session
upstream: http://search.cpan.org/dist/CGI-Application-Plugin-Session/
description: Plugin that adds session support to CGI
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
