name: perl-Config-INI
upstream: http://search.cpan.org/dist/Config-INI/
description: Config
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
