name: perl-CGI-Application-Plugin-FillInForm
upstream: http://search.cpan.org/dist/CGI-Application-Plugin-FillInForm/
description: Integrate with HTML
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
