name: perl-CGI-Application
upstream: http://search.cpan.org/dist/CGI-Application/
description: Framework for building reusable web-applications
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
