name: perl-ExtUtils-InferConfig
upstream: http://search.cpan.org/dist/ExtUtils-InferConfig/
description: Infer Perl Configuration for non-running interpreters
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
