name: oec-application
description: Use for check application compatibility with openEuler
upstream: https://gitee.com/openeuler/oec-application
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
