name: editorconfig
description: Parser for EditorConfig files written in C
upstream: https://github.com/editorconfig/editorconfig-core-c
branches:
- name: master
  type: protected
- name: openEuler-23.03
  type: protected
  create_from: master
- name: openEuler-23.09
  type: protected
  create_from: master
type: public
