name: R-pkgconfig
description: Private Configuration for 'R' Packages
upstream: https://github.com/r-lib/pkgconfig
branches:
- name: master
  type: protected
- name: openEuler-23.09
  type: protected
  create_from: master
type: public
