name: python-EditorConfig
upstream: http://editorconfig.org/
description: EditorConfig File Locator and Interpreter for Python
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
type: public
