name: python-sphinxcontrib-openapi
description: OpenAPI (fka Swagger) spec renderer for Sphinx.
upstream: https://github.com/sphinx-contrib/openapi
branches:
- name: master
  type: protected
type: public
