name: python-pytoolconfig
description: Python Tool Configuration to manage configuration for python tools and add support for a pyproject.toml configuration file. 
upstream: https://github.com/bageljrkhanofemus/pytoolconfig
branches:
- name: master
  type: protected
type: public
