name: python-os-collect-config
description: Collect and cache metadata, run hooks on changes.
upstream: https://opendev.org/openstack/os-collect-config
branches:
- name: master
  type: protected
- name: openEuler-20.03-LTS-Next
  type: readonly
  create_from: master
type: public
