name: python-os-apply-config
description: Apply configuration from cloud metadata(JSON).
upstream: https://opendev.org/openstack/os-apply-config
branches:
- name: master
  type: protected
- name: openEuler-20.03-LTS-Next
  type: readonly
  create_from: master
type: public
