name: cinnamon-settings-daemon
description: The settings daemon for the Cinnamon desktop.
upstream: https://github.com/linuxmint/cinnamon-settings-daemon
branches:
- name: master
  type: protected
- name: openEuler-22.09
  type: protected
  create_from: master
- name: openEuler-23.03
  type: protected
  create_from: master
- name: openEuler-23.09
  type: protected
  create_from: master
type: public
