name: kdebugsettings
description: Application to choose which QLoggingCategory are displayed
upstream: https://invent.kde.org/utilities/kdebugsettings
branches:
- name: master
  type: protected
type: public